### ISSUE TITLE
Recentering of the text

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix-generator#167]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

We can a bug in the email part in the recent commit which centres the text.
And this makes the design differ from that of the open-event too.
<img width="477" alt="screen shot 2018-06-21 at 19 05 55" src="https://user-images.githubusercontent.com/15213246/41722490-58b4b52a-7586-11e8-9217-ba053e649fb9.png">
New One
<img width="450" alt="screen shot 2018-06-21 at 19 06 05" src="https://user-images.githubusercontent.com/15213246/41722494-5b584774-7586-11e8-9749-76340dfe85c5.png">
Old One
<img width="413" alt="screen shot 2018-06-21 at 19 06 16" src="https://user-images.githubusercontent.com/15213246/41722499-5e981e78-7586-11e8-859a-144e10e3bc66.png">
Open-Event

**Comment by meets2tarun** [comment]
https://github.com/fossasia/meilix-generator/pull/165

**Comment by niccokunzmann** [comment]
@meets2tarun Thanks for the PR. Since this is a revert, I guess it was not possible for @rpotter12 to see that we have a design guideline. Would you be willing to add some sentences about working on HTML code and the design guideline/HTML guideline? This can also be in a different PR. Because: I would like to have this decision transparent for new-comers.
Currently, I cannot refer to a document that tells me that reverting this is right. #peopleBeforeCode

**Comment by meets2tarun** [comment]
Solved by the above PR
